Repository nextcloud/twofactor_nextcloud_notification, pull requests merged in 2024-03, with the labels that each got.

#806 chore(release): Bump version and add changelog
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#808 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/psalm-matrix.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: 3. to review, dependencies, automated

#809 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies
