Repository nextcloud/twofactor_nextcloud_notification, pull requests merged in 2024-08, with the labels that each got.

#849 Add Reuse compliance
  .eslintrc.js
  .github/contributing.md
  .github/dependabot.yml
  .github/issue_template.md.license
  .github/workflows/reuse.yml
  .gitignore
  .nextcloudignore
  .php-cs-fixer.dist.php
  AUTHORS.md
  CHANGELOG.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  Makefile
  README.md
  REUSE.toml
  appinfo/info.xml
  appinfo/routes.php
  babel.config.js
  krankerl.toml
  lib/AppInfo/Application.php
  lib/BackgroundJob/CleanupTokens.php
  lib/Controller/APIController.php
  lib/Controller/SettingsController.php
  lib/Db/Token.php
  lib/Db/TokenMapper.php
  lib/Event/StateChanged.php
  lib/Exception/TokenExpireException.php
  lib/Listener/RegistryUpdater.php
  lib/Migration/Version0001Date20180411172140.php
  lib/Migration/Version3004Date20220331145316.php
  lib/Notification/Notifier.php
  lib/Provider/NotificationProvider.php
  lib/Service/NotificationManager.php
  lib/Service/StateManager.php
  lib/Service/TokenManager.php
  lib/Settings/Personal.php
  package.json
  psalm.xml
  screenshots/android.png.license
  screenshots/notification.png.license
  screenshots/request.png.license
  src/challenge.js
  src/components/Challenge.vue
  src/components/PersonalSettings.vue
  src/mixins/Nextcloud.js
  src/services/SettingsService.js
  src/settings.js
  src/store.js
  src/util/poll.js
  stylelint.config.js
  templates/challenge.php
  templates/personal.php
  tests/psalm-baseline.xml.license
  webpack.js
Labels: 3. to review, technical debt

#844 fix: Use dedicated app icon
  LICENSES/Apache-2.0.txt
  REUSE.toml
  img/app-dark.svg
  img/app.svg
  lib/Notification/Notifier.php
  lib/Provider/NotificationProvider.php
Labels: 3. to review

#851 Add compile action
  .github/workflows/command-compile.yml
Labels: 4. to release

#846 fix: Add compiled JS to repo
  .gitignore
  LICENSES/BSD-3-Clause.txt
  LICENSES/ISC.txt
  LICENSES/MPL-2.0.txt
  build-js/WebpackSPDXPlugin.js
  build-js/npm-post-build.sh
  js/twofactor_nextcloud_notification-challenge.js
  js/twofactor_nextcloud_notification-challenge.js.license
  js/twofactor_nextcloud_notification-challenge.js.map
  js/twofactor_nextcloud_notification-challenge.js.map.license
  js/twofactor_nextcloud_notification-settings.js
  js/twofactor_nextcloud_notification-settings.js.license
  js/twofactor_nextcloud_notification-settings.js.map
  js/twofactor_nextcloud_notification-settings.js.map.license
  package-lock.json
  package.json
  webpack.js
Labels: 3. to review

#852 Run scheduled npm audit command
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review, technical debt

#854 [main] Fix npm audit
  js/twofactor_nextcloud_notification-challenge.js
  js/twofactor_nextcloud_notification-challenge.js.map
  js/twofactor_nextcloud_notification-settings.js
  js/twofactor_nextcloud_notification-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#856 fix(notification): Update notification code to new exceptions from Ne…
  lib/Notification/Notifier.php
Labels: 3. to review

#860 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#859 [stable30] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#863 fix(icon): Use a better icon for the notification
  REUSE.toml
  img/login-dark.svg
  lib/Notification/Notifier.php
Labels: 3. to review, backport-request

#865 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/reuse.yml
Labels: 3. to review, dependencies, automated

#868 [stable30] Fix npm audit
  js/twofactor_nextcloud_notification-challenge.js
  js/twofactor_nextcloud_notification-challenge.js.license
  js/twofactor_nextcloud_notification-challenge.js.map
  js/twofactor_nextcloud_notification-settings.js
  js/twofactor_nextcloud_notification-settings.js.license
  js/twofactor_nextcloud_notification-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#869 [main] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
