Repository nextcloud/twofactor_nextcloud_notification, pull requests merged in 2025-06, with the labels that each got.

#1017 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1016 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1019 ci: Move dev dependencies into vendor-bin
  .github/workflows/update-nextcloud-ocp.yml
  .gitignore
  .php-cs-fixer.dist.php
  REUSE.toml
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/BackgroundJob/CleanupTokens.php
  lib/Listener/RegistryUpdater.php
  lib/Migration/Version0001Date20180411172140.php
  lib/Migration/Version3004Date20220331145316.php
  lib/Migration/Version4000Date20240802134536.php
  lib/Migration/Version4000Date20240802134537.php
  lib/Notification/Notifier.php
  lib/Provider/NotificationProvider.php
  lib/Settings/Personal.php
  psalm.xml
  tests/psalm-baseline.xml
  vendor-bin/csfixer/composer.json
  vendor-bin/csfixer/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 4. to release

#1021 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1023 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1022 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1025 ci: update npm-audit-fix.yml workflow from template
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies
